title: La Garriga
views:
  - title: ALL
    badges:
      - entity: sensor.temperaturas_jardin_temperature
      - entity: sensor.temperaturas_jardin_temperature_2
      - entity: sensor.aire_salon_temperature
      - entity: sensor.aire_pasillo_temperature
      - entity: sensor.aire_estudio_temperature
    cards:
      - type: vertical-stack
        cards:
          - type: 'custom:dual-gauge-card'
            title: Auto
            cardwidth: 300
            min: 0
            max: 100
            outer:
              entity: sensor.fronius_self_sufficiency
              label: suf
              unit: '%'
              colors:
                - color: var(--label-badge-green)
                  value: 90
                - color: var(--label-badge-yellow)
                  value: 50
                - color: var(--label-badge-red)
                  value: 0
            inner:
              entity: sensor.fronius_self_consumption
              label: con
              unit: '%'
              colors:
                - color: var(--label-badge-green)
                  value: 0
                - color: var(--label-badge-yellow)
                  value: 99
                - color: var(--label-badge-red)
                  value: 100
          - type: gauge
            max: 6
            entity: sensor.fronius_balance_neto_hour
            severity:
              green: 0
              yellow: -1
              red: -5
            min: -6
            name: Balance neto horario
          - type: gauge
            min: 0
            max: 7000
            entity: sensor.fronius_pv_power
            severity:
              green: 4000
              yellow: 2000
              red: 0
            name: Producción solar
      - entities:
          - entity: sensor.fronius_house_power
            icon: 'mdi:gauge'
            name: Consumo vivienda
          - entity: sensor.fronius_grid_power
            icon: 'mdi:gauge'
            name: Consumo red
          - entity: sensor.fronius_house_energy_today
            name: Vivienda
          - entity: sensor.fronius_grid_energy_today
            icon: 'mdi:transmission-tower'
            name: Red
          - entity: sensor.fronius_self_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.fronius_grid_returned_energy_today
            icon: 'mdi:transmission-tower'
            name: Vertida
          - entity: sensor.fronius_balance_neto_today
            name: Balance neto
          - entity: sensor.fronius_pv_energy_today
            icon: 'mdi:solar-panel'
            name: Producida
          - entity: sensor.grid_voltage
            name: Tensión entrada
          - entity: switch.calefaccion
            icon: 'mdi:power-plug'
            name: Calefacción
        type: entities
        show_header_toggle: false
      - entities:
          - entity: sensor.aires_potencia
            icon: 'mdi:gauge'
          - entity: sensor.electrodomesticos_potencia
            icon: 'mdi:gauge'
          - entity: sensor.informatica_potencia
            name: Informática
            icon: 'mdi:gauge'
          - entity: sensor.aires_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.electrodomesticos_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.informatica_energy_today
            name: Informática hoy
            icon: 'mdi:transmission-tower'
        title: Consumos
        type: entities
      - entities:
          - entity: group.luces_exteriores
            icon: 'mdi:string-lights'
          - entity: group.luces_planta_2
            icon: 'mdi:string-lights'
          - entity: group.luces_planta_1
            icon: 'mdi:string-lights'
          - entity: group.luces_planta_baja
            icon: 'mdi:string-lights'
          - entity: group.luces_parking
            icon: 'mdi:string-lights'
        title: Luces
        type: entities
      - entity: weather.openweathermap
        type: weather-forecast
        name: La Garriga
  - title: ELE
    path: ele
    visible:
      - user: 0b501aacecfb42bba904a2e4e4a68859
      - user: 6117ab5599b94381b0d5b14cccd42e3c
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.tv_kitchen_power
            icon: 'mdi:gauge'
            name: TV cocina
          - entity: switch.tv_kitchen
            name: TV cocina
            icon: 'mdi:power-plug'
        title: TV
      - entities:
          - entity: sensor.induccion_power_adjust
            icon: 'mdi:gauge'
            name: Inducción
          - entity: sensor.horno_power
            icon: 'mdi:gauge'
            name: Horno + microondas
          - entity: sensor.microondas_power
            icon: 'mdi:gauge'
            name: Thermomix + nespresso
          - entity: sensor.lavadora_power
            icon: 'mdi:gauge'
          - entity: sensor.secadora_power
            icon: 'mdi:gauge'
          - entity: sensor.lavavajillas_power
            icon: 'mdi:gauge'
          - entity: sensor.nevera_power
            name: Nevera
            icon: 'mdi:gauge'
        title: Electrodomésticos
        type: entities
      - type: entities
        entities:
          - entity: sensor.induccion_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.horno_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.microondas_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.lavadora_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.secadora_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.lavavajillas_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.nevera_energy_today
            icon: 'mdi:transmission-tower'
        title: Energía
  - title: IT
    path: it
    visible:
      - user: 0b501aacecfb42bba904a2e4e4a68859
      - user: 6117ab5599b94381b0d5b14cccd42e3c
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.pc_agusti_power
            icon: 'mdi:gauge'
            name: PC Agustí
          - entity: sensor.pc_albert_power
            name: PC Albert
            icon: 'mdi:gauge'
          - entity: sensor.pc_despacho_power
            icon: 'mdi:gauge'
            name: PC despacho
          - entity: sensor.informatica_energy_today
            icon: 'mdi:transmission-tower'
        title: Informática
        show_header_toggle: false
  - title: EXT
    path: pe
    visible:
      - user: 0b501aacecfb42bba904a2e4e4a68859
      - user: 6117ab5599b94381b0d5b14cccd42e3c
    badges:
      - entity: sensor.temperaturas_jardin_temperature
      - entity: sensor.temperaturas_jardin_temperature_2
      - entity: sensor.humedad_jardin
    cards:
      - type: entities
        entities:
          - entity: switch.pastor
            icon: 'mdi:power-plug'
            name: Jardín
          - entity: sensor.pastor_power
            icon: 'mdi:gauge'
            name: Jardín
      - type: sensor
        entity: sensor.temperaturas_jardin_temperature
        graph: line
        name: Temperatura aire
        detail: 2
      - type: sensor
        entity: sensor.temperaturas_jardin_temperature_2
        graph: line
        name: Temperatura invernadero
        detail: 2
      - type: sensor
        entity: sensor.temperaturas_jardin_temperature_3
        graph: line
        name: Temperatura substrato
        detail: 2
      - type: sensor
        entity: sensor.invernadero_humidity
        graph: line
        name: Humedad invernadero
        detail: 2
  - path: pb
    title: PB
    badges:
      - entity: sensor.aire_salon_temperature
      - entity: sensor.aire_salon_humidity
    cards:
      - entity: climate.aire_salon
        type: thermostat
      - entities:
          - entity: sensor.aire_salon_power
            icon: 'mdi:gauge'
          - entity: sensor.aire_salon_energy_today
            icon: 'mdi:transmission-tower'
        show_header_toggle: false
        type: entities
      - double_tap_action:
          action: none
        entity: light.luz_comedor
        type: light
      - entity: light.luz_sofa
        type: light
      - entities:
          - entity: switch.luz_entrada
            icon: 'mdi:lightbulb'
          - entity: switch.luz_despacho
            icon: 'mdi:lightbulb'
          - entity: switch.luz_aseo
            icon: 'mdi:lightbulb'
          - entity: switch.extractor_aseo
            icon: 'mdi:power-plug'
          - entity: switch.luz_caldera
            icon: 'mdi:lightbulb'
          - entity: switch.luz_cocina
            icon: 'mdi:lightbulb'
        title: Luces
        type: entities
  - path: p1
    title: P1
    badges:
      - entity: sensor.aire_pasillo_temperature
      - entity: sensor.aire_pasillo_humidity
    cards:
      - entity: climate.aire_pasillo
        type: thermostat
      - entities:
          - entity: sensor.aire_pasillo_power
            icon: 'mdi:gauge'
          - entity: sensor.aire_pasillo_energy_today
            icon: 'mdi:transmission-tower'
        show_header_toggle: false
        type: entities
      - entities:
          - entity: switch.luz_pasillo_escalera
            icon: 'mdi:lightbulb'
          - entity: switch.luz_pasillo
            icon: 'mdi:lightbulb'
          - entity: switch.luz_bano
            icon: 'mdi:lightbulb'
          - entity: switch.luz_ducha
            icon: 'mdi:lightbulb'
          - entity: switch.luz_albert
            icon: 'mdi:lightbulb'
          - entity: switch.luz_mireia
            icon: 'mdi:lightbulb'
        title: Luces
        type: entities
  - path: p2
    title: P2
    badges:
      - entity: sensor.aire_estudio_temperature
      - entity: sensor.aire_estudio_humidity
    cards:
      - entity: climate.aire_estudio
        type: thermostat
      - entities:
          - entity: sensor.aire_estudio_power
            icon: 'mdi:gauge'
          - entity: sensor.aire_estudio_energy_today
            icon: 'mdi:transmission-tower'
        show_header_toggle: false
        type: entities
      - entities:
          - entity: switch.luz_escalera_estudio
            icon: 'mdi:lightbulb'
          - entity: switch.luz_estudio
            icon: 'mdi:lightbulb'
        title: Luces
        type: entities
      - entities:
          - entity: sensor.iqas_power
            name: freeDS
            icon: 'mdi:gauge'
          - entity: switch.iqas
            name: freeDS
            icon: 'mdi:power-plug'
          - entity: sensor.iqas_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.iqas_energy_yesterday
            icon: 'mdi:transmission-tower'
          - entity: sensor.iqas_energy_before_yesterday
            icon: 'mdi:transmission-tower'
        title: Radiador
        type: entities
        show_header_toggle: false
  - title: FRONIUS
    path: test
    badges: []
    cards:
      - entities:
          - entity: sensor.fronius_house_energy_hour
            name: Vivienda
          - entity: sensor.fronius_grid_energy_hour
            name: Red
          - entity: sensor.fronius_grid_returned_energy_hour
            name: Vertida
        type: entities
        show_header_toggle: false
        title: Energía Horaria
      - type: entities
        entities:
          - entity: sensor.fronius_house_energy_today
            name: Vivienda
          - entity: sensor.fronius_self_energy_today
            icon: 'mdi:transmission-tower'
          - entity: sensor.fronius_grid_energy_today
            name: 'Red '
          - entity: sensor.fronius_grid_returned_energy_today
            name: Vertida
          - entity: sensor.fronius_balance_neto_today
            name: Balance neto
          - entity: sensor.fronius_pv_energy_today
            icon: 'mdi:solar-panel'
            name: Producida
        title: Energía diaria

