sensor:
#------------------------------------------------------  FRONIUS BASIC  -----------------------------------------------------------
  - platform: fronius_basic
    ip_address: 192.168.1.6
    scan_interval: 4



#------------------------------------------------------  END OF DOCUMENT  ---------------------------------------------------------
