sensor:
#------------------------------------------------------  FRONIUS BASIC  -----------------------------------------------------------
  - platform: fronius_basic
    ip_address: 192.168.1.6




#------------------------------------------------------  END OF DOCUMENT  ---------------------------------------------------------
